### ISSUE TITLE
Front-End Music Player

### ISSUE THREAD

**Issue by marcusats** [fferrer89/streaming-service#18]
Work on implementing the front-end for the main app navigation bar, it will have a link to the user-profile. The music player, and to link for the Main page and the search page. Create new branch for development. Music player part should be its own component, I will add the logic for the queries, you can work on the design implementation. If there is a song selected the music player will show the song img the countdown of the song. I will attach screen shots of design.
<img width="275" alt="Screenshot 2024-04-22 at 5 58 46 PM" src="https://github.com/fferrer89/streaming-service/assets/90633967/c24b9127-2f42-45b4-9047-189ccbf99e52">
<img width="200" alt="Screenshot 2024-04-22 at 5 59 23 PM" src="https://github.com/fferrer89/streaming-service/assets/90633967/5fefb6ca-628d-4c8f-b543-fde8cf1fdc44">

**Comment by fferrer89** [comment]
This has been completed. See pull request below for more info:
https://github.com/fferrer89/streaming-service/pull/42

![Screenshot 2024-04-28 at 8 04 16 PM](https://github.com/fferrer89/streaming-service/assets/59100314/5c140b04-1f50-4b37-b46b-1c249794f34c)
