### ISSUE TITLE
Portal - Page

### ISSUE THREAD

**Issue by marcusats** [fferrer89/streaming-service#2]

**Comment by fferrer89** [comment]
@marcusats  - Please attach the pages to the original story instead of creating new stories (https://github.com/fferrer89/streaming-service/issues/3) if you dont mind. Closing this one.

**Comment by fferrer89** [comment]
@marcusats  - Please attach the pages to the original story instead of creating new stories (https://github.com/fferrer89/streaming-service/issues/3) if you dont mind. Closing this one.
