### ISSUE TITLE
Create the Mongo DB and S3 Schema

### ISSUE THREAD

**Issue by fferrer89** [fferrer89/streaming-service#4]
Database: Deternine the database to be used to store the app persistent data (users, products, ...) and design the schema.  Attach the schema documents to this page.

**Comment by bhavin79** [comment]
[Database Schema.pdf](https://github.com/fferrer89/streaming-service/files/14924628/Database.Schema.pdf)

**Comment by fferrer89** [comment]
Completed! Attached DB Schema
