### ISSUE TITLE
Create Mongose database squema

### ISSUE THREAD

**Issue by fferrer89** [fferrer89/streaming-service#7]
Implement the OOS for the MongoDB database for the field validation

**Comment by fferrer89** [comment]
@AchantaTharun - Please attach the schema to this story when completed!

**Comment by AchantaTharun** [comment]
Hi Team,

please find the initial sb schema here -> 
![](https://github.com/fferrer89/streaming-service/blob/main/streaming-service-backend/docs/schema/initial_schema.png)

Implemented the following,
1) Mongoose Models for user, artist, song, album, playlist, listeningHitstory
2) Add validation to fields
3) Create a sample seed.js file
4) Implemented sample resolver for user in graphql
